In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
paragraph = """
Modi was born and raised in Vadnagar in northeastern Gujarat, where he completed his secondary education. He was introduced to the RSS at the age of eight. His account of helping his father sell tea at the Vadnagar railway station has not been reliably corroborated. At age 18, he was married to Jashodaben Modi, whom he abandoned soon after, only publicly acknowledging her four decades later when legally required to do so. Modi became a full-time worker for the RSS in Gujarat in 1971. The RSS assigned him to the BJP in 1985 and he held several positions within the party hierarchy until 2001, rising to the rank of general secretary.[c]In 2001, Modi was appointed Chief Minister of Gujarat and elected to the legislative assembly soon after. His administration is considered complicit in the 2002 Gujarat riots,[d] and has been criticised for its management of the crisis. A little over 1,000 people were killed, according to official records, three-quarters of whom were Muslim; independent sources estimated 2,000 deaths, mostly Muslim.[11] A Special Investigation Team appointed by the Supreme Court of India in 2012 found no evidence to initiate prosecution proceedings against him.[e] While his policies as chief minister, which were credited for encouraging economic growth, were praised, Modi's administration was criticised for failing to significantly improve health, poverty and education indices in the state.[f] 

In the 2014 Indian general election, Modi led the BJP to a parliamentary majority, the first for a party since 1984. His administration increased direct foreign investment, and it reduced spending on healthcare, education, and social-welfare programmes. Modi began a high-profile sanitation campaign, controversially initiated the 2016 demonetisation of high-denomination banknotes and introduced the Goods and Services Tax, and weakened or abolished environmental and labour laws.
"""

In [3]:
paragraph

"\nModi was born and raised in Vadnagar in northeastern Gujarat, where he completed his secondary education. He was introduced to the RSS at the age of eight. His account of helping his father sell tea at the Vadnagar railway station has not been reliably corroborated. At age 18, he was married to Jashodaben Modi, whom he abandoned soon after, only publicly acknowledging her four decades later when legally required to do so. Modi became a full-time worker for the RSS in Gujarat in 1971. The RSS assigned him to the BJP in 1985 and he held several positions within the party hierarchy until 2001, rising to the rank of general secretary.[c]In 2001, Modi was appointed Chief Minister of Gujarat and elected to the legislative assembly soon after. His administration is considered complicit in the 2002 Gujarat riots,[d] and has been criticised for its management of the crisis. A little over 1,000 people were killed, according to official records, three-quarters of whom were Muslim; independent 

In [4]:
import nltk
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords

In [5]:
# Tokenization -- paragraphs - sentences- words 

# nltk.download('punkt')
sentences=nltk.sent_tokenize(paragraph)
sentences

['\nModi was born and raised in Vadnagar in northeastern Gujarat, where he completed his secondary education.',
 'He was introduced to the RSS at the age of eight.',
 'His account of helping his father sell tea at the Vadnagar railway station has not been reliably corroborated.',
 'At age 18, he was married to Jashodaben Modi, whom he abandoned soon after, only publicly acknowledging her four decades later when legally required to do so.',
 'Modi became a full-time worker for the RSS in Gujarat in 1971.',
 'The RSS assigned him to the BJP in 1985 and he held several positions within the party hierarchy until 2001, rising to the rank of general secretary.',
 '[c]In 2001, Modi was appointed Chief Minister of Gujarat and elected to the legislative assembly soon after.',
 'His administration is considered complicit in the 2002 Gujarat riots,[d] and has been criticised for its management of the crisis.',
 'A little over 1,000 people were killed, according to official records, three-quarters

In [6]:
# example of lemmatization
from nltk.stem import WordNetLemmatizer
# nltk.download('wordnet')
# nltk.download('stopwords')
lemmatizer=WordNetLemmatizer()
lemmatizer.lemmatize('goes')


In [15]:
len(sentences)

14

In [16]:
# clean the text, spcl char
import re

corpus=[]
for i in range(len(sentences)):
    review=re.sub('[^a-zA-Z]',' ',sentences[i])
    review=review.lower()
    corpus.append(review)

In [17]:
corpus

[' modi was born and raised in vadnagar in northeastern gujarat  where he completed his secondary education ',
 'he was introduced to the rss at the age of eight ',
 'his account of helping his father sell tea at the vadnagar railway station has not been reliably corroborated ',
 'at age     he was married to jashodaben modi  whom he abandoned soon after  only publicly acknowledging her four decades later when legally required to do so ',
 'modi became a full time worker for the rss in gujarat in      ',
 'the rss assigned him to the bjp in      and he held several positions within the party hierarchy until       rising to the rank of general secretary ',
 ' c in       modi was appointed chief minister of gujarat and elected to the legislative assembly soon after ',
 'his administration is considered complicit in the      gujarat riots  d  and has been criticised for its management of the crisis ',
 'a little over       people were killed  according to official records  three quarters 

In [18]:
stemmer=PorterStemmer()

In [19]:
# Applying stemming
for i in corpus:
    # print(i)
    words=nltk.word_tokenize(i)
    for word in words:
        if word not in set(stopwords.words('english')):
            print(stemmer.stem(word)) 

modi
born
rais
vadnagar
northeastern
gujarat
complet
secondari
educ
introduc
rss
age
eight
account
help
father
sell
tea
vadnagar
railway
station
reliabl
corrobor
age
marri
jashodaben
modi
abandon
soon
publicli
acknowledg
four
decad
later
legal
requir
modi
becam
full
time
worker
rss
gujarat
rss
assign
bjp
held
sever
posit
within
parti
hierarchi
rise
rank
gener
secretari
c
modi
appoint
chief
minist
gujarat
elect
legisl
assembl
soon
administr
consid
complicit
gujarat
riot
criticis
manag
crisi
littl
peopl
kill
accord
offici
record
three
quarter
muslim
independ
sourc
estim
death
mostli
muslim
special
investig
team
appoint
suprem
court
india
found
evid
initi
prosecut
proceed
e
polici
chief
minist
credit
encourag
econom
growth
prais
modi
administr
criticis
fail
significantli
improv
health
poverti
educ
indic
state
f
indian
gener
elect
modi
led
bjp
parliamentari
major
first
parti
sinc
administr
increas
direct
foreign
invest
reduc
spend
healthcar
educ
social
welfar
programm
modi
began
high
profi

In [20]:
stopwords.words('english')

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [21]:
# lemmatization
for i in corpus:
    # print(i)
    words=nltk.word_tokenize(i)
    for word in words:
        if word not in set(stopwords.words('english')):
            print(lemmatizer.lemmatize(word)) 

modi
born
raised
vadnagar
northeastern
gujarat
completed
secondary
education
introduced
r
age
eight
account
helping
father
sell
tea
vadnagar
railway
station
reliably
corroborated
age
married
jashodaben
modi
abandoned
soon
publicly
acknowledging
four
decade
later
legally
required
modi
became
full
time
worker
r
gujarat
r
assigned
bjp
held
several
position
within
party
hierarchy
rising
rank
general
secretary
c
modi
appointed
chief
minister
gujarat
elected
legislative
assembly
soon
administration
considered
complicit
gujarat
riot
criticised
management
crisis
little
people
killed
according
official
record
three
quarter
muslim
independent
source
estimated
death
mostly
muslim
special
investigation
team
appointed
supreme
court
india
found
evidence
initiate
prosecution
proceeding
e
policy
chief
minister
credited
encouraging
economic
growth
praised
modi
administration
criticised
failing
significantly
improve
health
poverty
education
index
state
f
indian
general
election
modi
led
bjp
parliamentar

In [ ]:
# Bag of words example
from sklearn.feature_extraction.text import CountVectorizer

# Sample documents
documents = [
    "This is the first document.",
    "This document is the second document.",
    "And this is the third one.",
    "Is this the first document?",
]

# Initialize CountVectorizer
vectorizer = CountVectorizer()

# Fit the vectorizer to the documents and transform the documents into a matrix of token counts
X = vectorizer.fit_transform(documents)

# Convert the matrix to an array for better visualization
X_array = X.toarray()

# Get the feature names (unique words)
feature_names = vectorizer.get_feature_names_out()

# Print the matrix and feature names
print("Matrix of token counts:")
print(X_array)
print("\nFeature names:")
print(feature_names)



Matrix of token counts:
[[0 1 1 1 0 0 1 0 1]
 [0 2 0 1 0 1 1 0 1]
 [1 0 0 1 1 0 1 1 1]
 [0 1 1 1 0 0 1 0 1]]

Feature names:
['and' 'document' 'first' 'is' 'one' 'second' 'the' 'third' 'this']


In [22]:
# bag of words
from sklearn.feature_extraction.text import CountVectorizer

cv=CountVectorizer(binary=False)
# cv=CountVectorizer(binary=False,ngram_range=(3,3)) # ngrams example 3,3 gives three words together n 2,3 give 2 , 3 words words
# cv=CountVectorizer(binary=False,ngram_range=(2,3))
X=cv.fit_transform(corpus)
cv.vocabulary_

{'modi': 99,
 'was': 160,
 'born': 20,
 'and': 9,
 'raised': 125,
 'in': 72,
 'vadnagar': 159,
 'northeastern': 103,
 'gujarat': 59,
 'where': 165,
 'he': 61,
 'completed': 24,
 'his': 70,
 'secondary': 135,
 'education': 40,
 'introduced': 80,
 'to': 157,
 'the': 154,
 'rss': 133,
 'at': 14,
 'age': 8,
 'of': 105,
 'eight': 41,
 'account': 3,
 'helping': 65,
 'father': 49,
 'sell': 137,
 'tea': 152,
 'railway': 124,
 'station': 149,
 'has': 60,
 'not': 104,
 'been': 17,
 'reliably': 129,
 'corroborated': 28,
 'married': 97,
 'jashodaben': 86,
 'whom': 168,
 'abandoned': 0,
 'soon': 144,
 'after': 6,
 'only': 108,
 'publicly': 122,
 'acknowledging': 4,
 'her': 66,
 'four': 54,
 'decades': 34,
 'later': 89,
 'when': 164,
 'legally': 92,
 'required': 130,
 'do': 38,
 'so': 142,
 'became': 16,
 'full': 55,
 'time': 156,
 'worker': 170,
 'for': 51,
 'assigned': 13,
 'him': 69,
 'bjp': 19,
 'held': 64,
 'several': 139,
 'positions': 115,
 'within': 169,
 'party': 112,
 'hierarchy': 67,
 'un

In [23]:
corpus[0]

' modi was born and raised in vadnagar in northeastern gujarat  where he completed his secondary education '

In [24]:
X[0].toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0]], dtype=int64)

In [25]:
# Get the feature names (unique words)
feature_names = cv.get_feature_names_out()
feature_names 


array(['abandoned', 'abolished', 'according', 'account', 'acknowledging',
       'administration', 'after', 'against', 'age', 'and', 'appointed',
       'as', 'assembly', 'assigned', 'at', 'banknotes', 'became', 'been',
       'began', 'bjp', 'born', 'by', 'campaign', 'chief', 'completed',
       'complicit', 'considered', 'controversially', 'corroborated',
       'court', 'credited', 'crisis', 'criticised', 'deaths', 'decades',
       'demonetisation', 'denomination', 'direct', 'do', 'economic',
       'education', 'eight', 'elected', 'election', 'encouraging',
       'environmental', 'estimated', 'evidence', 'failing', 'father',
       'first', 'for', 'foreign', 'found', 'four', 'full', 'general',
       'goods', 'growth', 'gujarat', 'has', 'he', 'health', 'healthcare',
       'held', 'helping', 'her', 'hierarchy', 'high', 'him', 'his',
       'improve', 'in', 'increased', 'independent', 'india', 'indian',
       'indices', 'initiate', 'initiated', 'introduced', 'investigation',
    

In [26]:
cv=CountVectorizer(binary=True)  # when binary=True only 1/0 will be seen . Noother no. like 2,3 etc
X=cv.fit_transform(corpus)
X[0].toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0]], dtype=int64)

In [27]:
# apply stopwords -- sparse matrix becomes smaller

corpus=[]
for i in range(len(sentences)):
    review=re.sub('[^a-zA-Z]',' ',sentences[i])
    review=review.lower()
    review=review.split()
    review=[lemmatizer.lemmatize(word) for word in review if not word in set(stopwords.words('english'))]
    review=' '.join(review)
    corpus.append(review)

In [28]:
cv=CountVectorizer(binary=False)
X=cv.fit_transform(corpus)
cv.vocabulary_

{'modi': 81,
 'born': 14,
 'raised': 100,
 'vadnagar': 129,
 'northeastern': 84,
 'gujarat': 50,
 'completed': 17,
 'secondary': 109,
 'education': 32,
 'introduced': 65,
 'age': 6,
 'eight': 33,
 'account': 3,
 'helping': 54,
 'father': 41,
 'sell': 111,
 'tea': 125,
 'railway': 99,
 'station': 122,
 'reliably': 104,
 'corroborated': 21,
 'married': 79,
 'jashodaben': 68,
 'abandoned': 0,
 'soon': 117,
 'publicly': 97,
 'acknowledging': 4,
 'four': 45,
 'decade': 27,
 'later': 71,
 'legally': 74,
 'required': 105,
 'became': 11,
 'full': 46,
 'time': 128,
 'worker': 133,
 'assigned': 9,
 'bjp': 13,
 'held': 53,
 'several': 113,
 'position': 90,
 'within': 132,
 'party': 87,
 'hierarchy': 55,
 'rising': 107,
 'rank': 101,
 'general': 47,
 'secretary': 110,
 'appointed': 7,
 'chief': 16,
 'minister': 80,
 'elected': 34,
 'legislative': 75,
 'assembly': 8,
 'administration': 5,
 'considered': 19,
 'complicit': 18,
 'riot': 106,
 'criticised': 25,
 'management': 78,
 'crisis': 24,
 'littl

In [29]:
X[0].toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        0, 0]], dtype=int64)

In [30]:
# Get the feature names (unique words)
feature_names = cv.get_feature_names_out()
feature_names 

array(['abandoned', 'abolished', 'according', 'account', 'acknowledging',
       'administration', 'age', 'appointed', 'assembly', 'assigned',
       'banknote', 'became', 'began', 'bjp', 'born', 'campaign', 'chief',
       'completed', 'complicit', 'considered', 'controversially',
       'corroborated', 'court', 'credited', 'crisis', 'criticised',
       'death', 'decade', 'demonetisation', 'denomination', 'direct',
       'economic', 'education', 'eight', 'elected', 'election',
       'encouraging', 'environmental', 'estimated', 'evidence', 'failing',
       'father', 'first', 'foreign', 'found', 'four', 'full', 'general',
       'good', 'growth', 'gujarat', 'health', 'healthcare', 'held',
       'helping', 'hierarchy', 'high', 'improve', 'increased',
       'independent', 'index', 'india', 'indian', 'initiate', 'initiated',
       'introduced', 'investigation', 'investment', 'jashodaben',
       'killed', 'labour', 'later', 'law', 'led', 'legally',
       'legislative', 'little', 'm

In [40]:
# TFIDF

from sklearn.feature_extraction.text import TfidfVectorizer
cv=TfidfVectorizer()
# cv=TfidfVectorizer(ngram_range=(3,3)) # trigrams
# cv=TfidfVectorizer(ngram_range=(1,1), max_features=3) # top 3 high occuring features as results
X=cv.fit_transform(corpus)

In [41]:
corpus[0]

'modi born raised vadnagar northeastern gujarat completed secondary education'

In [42]:
X[0].toarray()

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.37480575,
        0.        , 0.        , 0.37480575, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.2886353 , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.26089461, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.  

# chk google colab notebook on github 

In [44]:
# pip install gensim  --nlp library having pretrained google news 300 dimensions